%% Step 1: Create an actor (patient actor)
% Azure Service Fabric  https://azure.microsoft.com/en-us/services/service-fabric/
% Azure Service Fabric Actor  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-introduction
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
createActorService = 'createActor';
requestUri = [nanoServiceBaseUri createActorService];
requestBody = struct('actorId', 'patient032904475');
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 2: Add a variable “bloodSodium” to the previously created patient actor. 
%  The variable value be “unknown” initially.
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
addVariableService = 'addVariable';
requestUri = [nanoServiceBaseUri addVariableService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'bloodSodium', 'value', 'unknown');
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 3: Get the value of the variable “bloodSodium” which is currently “unknown”.
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
getValueService = 'getValue';
requestUri = [nanoServiceBaseUri getValueService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'bloodSodium');
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 4: Set the value of the variable “bloodSodium” to 109. 
% When a new value for "bloodSodium" is set, it is published to Azure Event 
% Grid and the variable "hyponatremia" is automatically generated by the 
% Azure Function "HyponatremiaDDx" which decides whether there is 
% hyponatremia (< 135 mEq/L) or not.
% Azure Functions   https://azure.microsoft.com/en-us/services/functions/
% Azure Event Grid  https://azure.microsoft.com/en-us/services/event-grid/
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
setValueService = 'setValue';
requestUri = [nanoServiceBaseUri setValueService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'bloodSodium', 'value', 109);
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 5: Get the value of the variable “bloodSodium” which is now changed to 109.
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
getValueService = 'getValue';
requestUri = [nanoServiceBaseUri getValueService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'bloodSodium');
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 6: Get the value of the variable “hyponatremia” which is now “true”
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
getValueService = 'getValue';
requestUri = [nanoServiceBaseUri getValueService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'hyponatremia');
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 7: Set the value of the variable “bloodSodium” to 342. 
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
setValueService = 'setValue';
requestUri = [nanoServiceBaseUri setValueService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'bloodSodium', 'value', 342);
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 8: Get the value of the variable “hyponatremia” which is now "false".
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
getValueService = 'getValue';
requestUri = [nanoServiceBaseUri getValueService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'hyponatremia');
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)

%% Step 9: Remove the variable “bloodSodium”. 
nanoServiceBaseUri = 'http://csmlab7.uconn.edu/';
removeVariableService = 'removeVariable';
requestUri = [nanoServiceBaseUri removeVariableService]
requestBody = struct('actorId', 'patient032904475', 'variable', 'bloodSodium');
options = weboptions('MediaType','application/json');
response = webwrite(requestUri, requestBody, options)
